name: Build PHP 8.4 ARMHF

on: [push]

jobs:
  build-php:
    runs-on: ubuntu-latest
    container:
      image: arm32v7/ubuntu:22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y \
            build-essential \
            autoconf \
            wget \
            curl \
            unzip \
            libxml2-dev \
            libsqlite3-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libonig-dev \
            libjpeg-dev \
            libpng-dev \
            libwebp-dev \
            libfreetype6-dev \
            libzip-dev \
            zlib1g-dev \
            pkg-config \
            git

      - name: Download PHP 8.4 source
        run: |
          wget https://www.php.net/distributions/php-8.4.30.tar.gz
          tar xzf php-8.4.30.tar.gz

      - name: Configure & build PHP
        run: |
          cd php-8.4.30
          ./configure \
            --prefix=$PWD/install \
            --enable-mbstring \
            --with-curl \
            --with-openssl \
            --with-zlib \
            --enable-soap \
            --enable-intl \
            --with-pdo-mysql
          make -j$(nproc)
          make install

      - name: Upload ARMHF PHP binary
        uses: actions/upload-artifact@v4
        with:
          name: php-8.4-armhf
          path: php-8.4.30/install/
